spring.application.name=order-service

server.servlet.context-path=/orders
server.port=9020

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/OrderDb
spring.datasource.username=postgres
spring.datasource.password=avanish7080
spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

